server:
  port: 8083

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          react-client:
            registration:
              client-id: "react-client"
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods: "client_secret_basic"
              authorization-grant-types: "client_credentials"
              scopes: "user.read,user.write"
